{"name": "2.2 Личный кабинет. переход в раздел «История заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <personal_account_test.TestPasswordRecovery object at 0x77033f6ab7d0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"3b2111a3-08a6-462a-a960-2e3c4ce02364\")>\npayload = {'email': 'ngonzalez@example.org', 'name': 'antonio44', 'password': 'm%XL89YuKW'}, create_user = <Response [403]>\n\n    @allure.title('2.2 Личный кабинет. переход в раздел «История заказов»')\n    @allure.description('Личный кабинет. переход в раздел «История заказов»')\n    def test_personal_account_go_to_order_history(self, driver, payload, create_user):\n        personal_page = ProfilePage(driver)\n        personal_page.open_page(Urls.MAIN)\n>       personal_page.login_and_go_to_personal_account(payload)\n\ntests/personal_account_test.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/profile_page.py:16: in login_and_go_to_personal_account\n    self.wait_and_find_element(MainPageLocator.MAIN_TITLE)\npages/base_page.py:16: in wait_and_find_element\n    return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"3b2111a3-08a6-462a-a960-2e3c4ce02364\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x77033f6b9da0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "description": "Личный кабинет. переход в раздел «История заказов»", "steps": [{"name": "Открытие страницы", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/'"}], "start": 1727814059558, "stop": 1727814063993}, {"name": "Переход в личную страницу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/pages/profile_page.py\", line 16, in login_and_go_to_personal_account\n    self.wait_and_find_element(MainPageLocator.MAIN_TITLE)\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/pages/base_page.py\", line 16, in wait_and_find_element\n    return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидание видимости элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//h1[text()='Соберите бургер']\")"}], "start": 1727814063994, "stop": 1727814064063}, {"name": "Ожидание что по элементу можно кликнуть", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//p[text()='Личный Кабинет']\")"}], "start": 1727814064063, "stop": 1727814064116}, {"name": "Ожидание видимости элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//*[text()='Email']/../input\")"}], "start": 1727814064407, "stop": 1727814064421}, {"name": "Ожидание видимости элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//*[text()='Пароль']/../input\")"}], "start": 1727814064521, "stop": 1727814064544}, {"name": "Ожидание что по элементу можно кликнуть", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//button[text()='Войти']\")"}], "start": 1727814064581, "stop": 1727814064629}, {"name": "Ожидание видимости элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/pages/base_page.py\", line 16, in wait_and_find_element\n    return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/sv/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \"//h1[text()='Соберите бургер']\")"}], "start": 1727814064862, "stop": 1727814074946}], "parameters": [{"name": "payload", "value": "{'email': 'ngonzalez@example.org', 'password': 'm%XL89YuKW', 'name': 'antonio44'}"}], "start": 1727814063993, "stop": 1727814074953}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1727814059558, "stop": 1727814074955, "uuid": "7aa851e9-eb5c-488a-a26d-03ea3ad951a1", "historyId": "8b6ec493d87f36431e55e797423564cc", "testCaseId": "78d15467d5d57eb20f1273137140433d", "fullName": "tests.personal_account_test.TestPasswordRecovery#test_personal_account_go_to_order_history", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "personal_account_test"}, {"name": "subSuite", "value": "TestPasswordRecovery"}, {"name": "host", "value": "sv-laptop"}, {"name": "thread", "value": "53244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.personal_account_test"}]}